highlighter: rogue
permalink: /posts/:title
future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
url: http://thehackerwithin.github.com/illinois
name: Hacker Within
chapter: Illinois
description: An initial blog and site for THW at UI at Urbana-Champaign
twitter: hackerwithin_IL
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: hackerwithinadmin
include: ['_people']
relative_permalinks: false
